[plugin]
id = "azure-functions"
class = "org.ballerinax.azurefunctions.AzureCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/azure_functions-compiler-plugin-@project.version@.jar"
