[package]
org = "ballerinax"
name = "azure_functions"
version = "3.1.0"
distribution = "2201.3.0"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure.functions"
license = ["Apache-2.0"]
keywords = ["azure", "functions", "serverless", "cloud"]

[[platform.java11.dependency]]
path = "../native/build/libs/azure_functions-native-3.1.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/mime-native-2.5.0.jar"
