name: Daily build

on:
  schedule:
    - cron:  '0 */12 * * *'

jobs:
  build:
    if: github.repository_owner == 'ballerina-platform'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
        packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
      run: |
        ./gradlew clean build --scan --no-daemon
    - name: Generate Codecov Report
      uses: codecov/codecov-action@v1
