name: Ballerina Azure Functions Build

on:
  pull_request:
  push:
    branches-ignore:
      - master
      - "automated/dependency_version_update"
      - "automated/dependency_version_update_tmp"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      packageUser: ${{ github.actor }}
      packagePAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew build
      - name: Generate Codecov Report
        uses: codecov/codecov-action@v2
